### PR TITLE
Fix mob TP use chance to be more retail accurate

### LINKED ISSUE #184: Monsters gain TP rapidly when melee attack
<a href="https://github.com/ghost"></img></a> **Issue by [ghost](https://github.com/ghost)**
_Sunday Aug 06, 2017 at 06:24 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 3969_

----

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar - Issue ) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30170707_1

**_Server Version_** (type `revision` in game) **:** 
Revision: d428456385e41c5120155badf126d8c8c1981d88

**_Source Branch_** (master/stable) **:** Master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**
TeoTwawki asked me to report this here regarding DPS using the a pre2014 retail update to TP gain, http://ffxiclopedia.wikia.com/wiki/Tactical_Points

Just a very brief (not actual numbers) example: Using SAM as the example, SAM gains ~250tp per swing. SAM hits Fafnir, Fafnir gets 250tp. Where as Fafnir hits SAM, SAM gets ~50tp.

### LINKED ISSUE #1032: Enemies use their TP moves at incorrect intervals without regard for their current HP%
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://ffxiclopedia.fandom.com/wiki/Tactical_Points
"Monsters will use their TP semi-randomly when at 25% HP or above, until reaching 3000 TP at which point they will use it on one of their special attacks. Once monsters fall below 25% HP, they will no longer save their TP and will attempt to use their special attacks immediately upon reaching 1000 TP."

This is supposedly part of issue #184 as discussed in the last 1/3 of it, but that issue is very unclear and can likely be closed.

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #184 

Mobs will now use their TP moves "somewhat randomly" as expected when their HPP is > 25% and TP is between 1000-2999.

Thanks to @Kreidos for some feedback along the way.

### CODE REVIEW

**Comment by Kreidos** [comment]
As I mentioned on the discord, the 0.7% per tick seems a tad low to me. That'd be roughly a 40% chance to use a skill within 30 seconds. I leave it to someone with better retail knowledge than I to say whether this feels about right!

Good work, nonetheless. :+1:

**Comment by tankfest** [comment]
> 
> 
> As I mentioned on the discord, the 0.7% per tick seems a tad low to me. That'd be roughly a 40% chance to use a skill within 30 seconds. I leave it to someone with better retail knowledge than I can say whether this feels about right!

Upped to .92% per tick, which equates almost exactly to a 50% chance for the mob to use a skill within the first 30 seconds of it having 1000 tp.

For you non-statistics people:  Probability of a skill occuring at this rate within 75 ticks (or 30 seconds) = 1 - (1 - .0092)^75 = 0.5000

**Review by Kreidos — APPROVED** [review]
Looks good to me

File: src/map/entities/mobentity.cpp [hunk 1]
```diff
@@ -337,7 +337,7 @@ uint8 CMobEntity::TPUseChance()
 
     if (health.tp == 3000 || (GetHPP() <= 25 && health.tp >= 1000))
     {
-        return 100;
+        return 10000;
     }
 
     return (uint8)getMobMod(MOBMOD_TP_USE_CHANCE);
```
Comment (Kreidos) [inline src/map/entities/mobentity.cpp]: Not really critical on this occasion, but could change to uint16 to match the return type.

**Comment by TeoTwawki** [comment]
Ahh, makes sense now.. the tick rate used to be a larger time interval. when it decreased, the more frequent tp use was a side effect.

**Review by zach2good — APPROVED** [review]
Yessss statistics! Thanks for the explanation in the comments! Looks good

**Comment by 59blargedy** [comment]
we can do this, but i am not sure it is quite right. my  understanding is that tp usage is hp percentage based, above 50 mobs use tp at 3k, below 50 at 2k, below 25 at 1k.

**Comment by TeoTwawki** [comment]
he's got it back to what it used to be in any case. whether it ever should have had randomness, someone can prove/disprove that easily enough on retail just feeding a mob tp repeatedly and that'd be easy to change later.
