### PR TITLE
fix(ability): Increase duration and add accuracy bonus to Shiva's Sleepga

### LINKED ISSUE #257: Shiva's Sleepga doesn't use SMN calculation
<a href="https://github.com/davismj"></img></a> **Issue by [davismj](https://github.com/davismj)**
_Tuesday Jan 29, 2019 at 07:01 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 5674_

----

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar - Issue ) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type /ver in game) **:** 30181222_1

**_Source Branch_** (master/stable) **:** master

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Shiva's Sleepga depends on Summoner's Summoning Magic skill for accuracy. Typically, this looks like a buff to accuracy based on skill level over natural skill. Couldn't find any specific values.

### PR DESCRIPTION
**Pull request by davismj**
Duration was 60, should be 90 according to all sources.

The `applyPlayerResistance` method in monstertpmoves.lua had its signature updated a long time ago, changing the 5th argument from the spell school to the accuracy bonus. Sleepga was not updated and so was receiving a flat accuracy bonus of tpz.skill.ELEMENTAL_MAGIC (38, I think). I've removed that.

Accordiong to ffxiclopedia, Sleepga was supposed to receive an unknown accuracy bonus based on summoning skill. These generally are some factor of summoning magic skill over cap. I've added that bonus with a factor of 1.0.

Sources
- https://www.bg-wiki.com/bg/Sleepga_(Blood_Pact)
- https://ffxiclopedia.fandom.com/wiki/Sleepga_(Blood_Pact)
- http://wiki.ffo.jp/html/2230.html

Closes #257

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [ ] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

File: scripts/globals/abilities/pets/sleepga.lua [hunk 1]
```diff
@@ -5,15 +5,18 @@ require("scripts/globals/monstertpmoves")
...
     return 0, 0
 end
 
 function onPetAbility(target, pet, skill)
-    local duration = 60
-    local resm = applyPlayerResistance(pet, -1, target, pet:getStat(tpz.mod.INT)-target:getStat(tpz.mod.INT), tpz.skill.ELEMENTAL_MAGIC, 5)
+    local duration = 90
+    local dINT = pet:getStat(tpz.mod.INT) - target:getStat(tpz.mod.INT)
+    local bonus = getSummoningSkillOverCap(pet)
+    local resm = applyPlayerResistance(pet, -1, target, dINT, bonus, 5)
```
Comment (davismj) [inline scripts/globals/abilities/pets/sleepga.lua]: is there a table for ice element?

**Review by TeoTwawki — APPROVED** [review]
lgtm

File: scripts/globals/abilities/pets/sleepga.lua [hunk 2]
```diff
@@ -5,15 +5,19 @@ require("scripts/globals/monstertpmoves")
 require("scripts/globals/status")
 require("scripts/globals/magic")
 require("scripts/globals/msg")
+require("scripts/globals/spell_data")
```
Comment (zach2good) [inline scripts/globals/abilities/pets/sleepga.lua:8]: `spell_data` is already required by `magic`, no big deal, just reference for next time 👍

**Review by zach2good — APPROVED** [review]
Looks good, thanks!
