### PR TITLE
Fix Time-of-Day events not firing reliably (Night mobs not spawn/despawn)

### LINKED ISSUE #282: Undead do not despawn if no player is in the zone to cause tick
<a href="https://github.com/Bizzle-Dapp"></img></a> **Issue by [Bizzle-Dapp](https://github.com/Bizzle-Dapp)**
_Monday Apr 22, 2019 at 22:52 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 5882_

----

**_I have:_**
Initially noticed a Wight roaming Rolanberry fields in the middle of the daytime. Have since spotted Zombies in Pashlow Marshlands and a previous issue: github/DarkstarProject/darkstar - Issue 2570 references a very similar issue. 

- [x] searched existing issues (http://github.com/darkstarproject/darkstar - Issue ) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 30190328_2

**_Source Branch_** (master/stable) **:** Initially from whasf installer - since slightly editted

**_Additional Information_** (Steps to reproduce/Expected behavior) **:**  Likely all

### PR DESCRIPTION
**Pull request by Kreidos**
This fixes longstanding intermittent issues with Evening Mobs not spawning, not de-spawning, Day/Night Latents not always taking effect, guild shops not always restocking, and many more things which are dependent on reliable time-transition detections.

The long explanation of this problem is that the time_server runs based on a delay of 2400ms (one vanadiel minute), while the SyncTime() function uses the true system clock to generate the current Vanadiel Time. Since a delay-based sync cycle is variable given various system loads, conditions, and code execution, it will drift in and out of phase with the SyncTime() time generation, leading to vanadiel minutes periodically being skipped or repeated. If this skipped second was minute 0 of an hour, this would result in TOTD updates not firing.

TOTD updates are the only absolutely essential trigger based on this, and so should detect hour boundaries rather than "minute 0". I don't believe a rewrite of the clock mechanism is necessary or helpful, as the overall vanadiel timekeeping is still accurate; rather we just be cognizant of the granularity of its momentary accuracy.

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #282

### CODE REVIEW

**Comment by tankfest** [comment]
Such an annoying bug... such a seemingly simple fix... well done, sir.

**Comment by Kreidos** [comment]
> Such an annoying bug... such a seemingly simple fix... well done, sir.
Ha ha My father told me a story about a mechanic charging a customer $100 to turn one loose bolt which fixed a car that wouldn't start. When asking why a 1 minute fix was so expensive he replied it's $2 for the turn, and $98 for knowing _which_ bolt to turn.

This is one of those almost embarrassingly small fixes. It was just realizing the cause. :)

File: src/map/vana_time.cpp [hunk 1]
```diff
@@ -196,8 +196,10 @@ TIMETYPE CVanaTime::SyncTime()
     m_vHour = (uint32)((m_vanaDate % VTIME_DAY)   / VTIME_HOUR);
     m_vMin  = (uint32)( m_vanaDate % VTIME_HOUR);
 
-    if (m_vMin == 0)
+    static int8 lastTickedHour = m_vHour;
+    if (m_vHour == (lastTickedHour+1)%24)
```
Comment (ibm2431) [inline src/map/vana_time.cpp:200]: Does this `if` still fire if we're assigning `lastTickedHour` to be `m_vHour` right before checking if the current hour is our (just-assigned) `lastTicked` hour plus one?

**Review by ibm2431 — COMMENTED** [review]
The simplicity of the solution is/will be amazing; I'm just confused over timing of var assignments~

File: src/map/vana_time.cpp (hunk 1 above)
Comment (Kreidos) [reply src/map/vana_time.cpp:200]: Hey @ibm2431 ! It will, because I've declared `lastTickedHour` as static. Static variables are only initialized once the first time they're declared, and will have indefinite lifespan like globals do, but they still maintain local scope. I selected static rather than a class variable since this variable never needs to be used outside of this local function. :)

*Edit:* I felt I should clarify that this means line 199 only does something the first run-through.

Comment (cocosolos) [reply src/map/vana_time.cpp:200]: I actually had this same question lol. So the declaration happens once, then the reassignment happens every time?

Comment (Kreidos) [reply src/map/vana_time.cpp:200]: The declaration and assignment happens only once. Basically, after the first pass, line 199 is inert and does nothing. The only time it'll be assigned is after the following `if` statement is true, since I have an assignment statement in there.

Comment (cocosolos) [reply src/map/vana_time.cpp:200]: Yeah I meant the assignment on line 202. Makes sense, thanks for clarifying! Good work.

**Review by cocosolos — APPROVED** [review]

**Review by ibm2431 — APPROVED** [review]
