### PR TITLE
Flyers for Regine: final fixes, I swear

### LINKED ISSUE #865: Coullene  looks over curiously for a moment
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

This happens when Flyer for Regine hasn't been accepted.

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

* subtable npcData for faster lookups
* npcs will no longer look over curiously once you've traded them a flyer
* removed pre-quest dialog from Regine, per video and Nyu's retail testing
* removed npc flyer refusal dialog, per Nyu's retail testing
* localed some variables in npc scripts
* npcs will no longer look over curiously when you're not on the quest [Fixes #865]

### CODE REVIEW

**Review by Wiggo32 — APPROVED** [review]

File: scripts/zones/Southern_San_dOria/npcs/Cletae.lua [hunk 1]
```diff
@@ -5,20 +5,12 @@
...
 local ID = require("scripts/zones/Southern_San_dOria/IDs")
-require("scripts/globals/shop")
 require("scripts/globals/crafting")
-require("scripts/globals/settings")
 require("scripts/globals/status")
+require("scripts/globals/shop")
 -----------------------------------
 
 function onTrade(player,npc,trade)
-    if (FlyerForRegine == 1) then
```
Comment (ibm2431) [inline scripts/zones/Southern_San_dOria/npcs/Cletae.lua:15]: Gotta love the checks against variables which were never defined~

File: scripts/zones/Southern_San_dOria/npcs/Emoussine.lua [hunk 2]
```diff
@@ -4,18 +4,13 @@
...
-local ID = require("scripts/zones/Southern_San_dOria/IDs")
-require("scripts/globals/npc_util")
 require("scripts/globals/chocobo")
 -----------------------------------
 
 local eventSucceed = 600
 local eventFail    = 603
 
 function onTrade(player,npc,trade)
-    if player:getQuestStatus(SANDORIA,tpz.quest.id.sandoria.FLYERS_FOR_REGINE) == QUEST_ACCEPTED and npcUtil.tradeHas(trade, 532) then
```
Comment (ibm2431) [inline scripts/zones/Southern_San_dOria/npcs/Emoussine.lua:16]: And easy server crashes due to never having had the quest require!

File: scripts/zones/Southern_San_dOria/npcs/Glenne.lua [hunk 3]
```diff
@@ -4,11 +4,10 @@
 -- Starts and Finishes Quest: A Sentry's Peril
 -- !pos -122 -2 15 230
 -------------------------------------
-require("scripts/globals/settings");
-require("scripts/globals/titles");
-require("scripts/globals/shop");
```
Comment (ibm2431) [inline scripts/zones/Southern_San_dOria/npcs/Glenne.lua:9]: You were just _swimming_ in all the copy-paste code with never-used requires..!

File: scripts/zones/Southern_San_dOria/npcs/Machielle.lua [hunk 4]
```diff
@@ -3,18 +3,13 @@
 --  NPC: Machielle
 -- Norvallen Regional Merchant
 -----------------------------------
-require("scripts/globals/events/harvest_festivals")
 local ID = require("scripts/zones/Southern_San_dOria/IDs")
-require("scripts/globals/conquest")
-require("scripts/globals/npc_util")
-require("scripts/globals/quests")
+require("scripts/globals/events/harvest_festivals")
+require("scripts/globals/shop")
```
Comment (ibm2431) [inline scripts/zones/Southern_San_dOria/npcs/Machielle.lua:8]: @TeoTwawki [got a little _too_ crazy with the require axe-murdering](https://github.com/project-topaz/topaz/commit/1dabc64278c58bd98955185114871a985d2323e6#diff-deeb89c2eb94a5679b39cc32db080314) 😉

File: scripts/zones/Southern_San_dOria/npcs/Parvipon.lua [hunk 5]
```diff
@@ -4,30 +4,17 @@
...
         end
     end
-
-    -- "Flyers for Regine" conditional script    local count = trade:getItemCount();
-MagicFlyer = trade:hasItemQty(532,1);
-
-    if (MagicFlyer == true and count == 1) then
-        local FlyerForRegine = player:getQuestStatus(SANDORIA,tpz.quest.id.sandoria.FLYERS_FOR_REGINE);
-        if (FlyerForRegine == 1) then
-            player:messageSpecial(ID.text.FLYER_REFUSED);
```
Comment (ibm2431) [inline scripts/zones/Southern_San_dOria/npcs/Parvipon.lua:27]: I am amused by how many different forms this trade block took.

File: scripts/zones/Port_San_dOria/npcs/Regine.lua [hunk 6]
```diff
@@ -19,8 +19,6 @@ function onTrade(player,npc,trade)
         if (npcUtil.giveItem(player, 532)) then
             player:confirmTrade();
         end
-    elseif (flyersForRegine == QUEST_ACCEPTED and npcUtil.tradeHas(trade, 532)) then
-        player:messageSpecial(ID.text.FLYER_REFUSED);
```
Comment (ibm2431) [inline scripts/zones/Port_San_dOria/npcs/Regine.lua:23]: Regine: "I don't want this trash!"

**Review by ibm2431 — APPROVED** [review]
Try as I might, I wasn't able to find an over-eager removal of a require that a NPC still needed!

Nice work, Wren. I'm glad to see the vile tendrils of this quest purged from the fair city of San d'Oria.

Comments are just to show to others that I _was_ paying attention while reviewing~!

File: scripts/zones/Southern_San_dOria/npcs/Machielle.lua (hunk 4 above)
Comment (TeoTwawki) [reply scripts/zones/Southern_San_dOria/npcs/Machielle.lua:8]: :scream:
