### PR TITLE
Hunt System

### LINKED ISSUE #240: hunt regimes and dominion ops
<a href="https://github.com/TeoTwawki"></img></a> **Issue by [TeoTwawki](https://github.com/TeoTwawki)**
_Thursday Oct 11, 2018 at 16:08 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 5302_

----

**_I have:_**

- [x] searched existing issues (http://github.com/darkstarproject/darkstar - Issue ) to see if the issue I am posting has already been addressed or opened by another contributor
- [x] checked the commit log to see if my issue has been resolved since my server was last updated

**_Client Version_** (type `/ver` in game) **:** 
n/a

**_Source Branch_** (master/stable) **:** 
n/a

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

These can be easily scripted right now. 

Hunt Regimes are very similar to Fields of Valor but the targets are NMs and the rewards are evoliths instead of exp. This is separate from Elite FoV pages. The evolith item carries augments on it as if it were equipment. The only part we can't do is synergy to transfer the evolith's augment data onto equipment **because synergy doesn't exist yet.**

Dominion ops pages are similar to Fields of Valor for Abyssea zones. We don't yet have regional influence for dominion op zones and the mobs themselves aren't retail accurate\* yet but for testing the mob only needs to spawn and die properly and that already works 

\* (retail abyssea mobs have level changes when killed - the quicker you mow them down the stronger they get, and will delevel themselves back to normal once left idle for a time).

### PR DESCRIPTION
**Pull request by Apocarypse**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Functional hunt system implementation. The only thing missing is Evoliths, which require synergy to be working. The VNMs also do not have scripts, as they are unimplemented at this time.

Please do not squash when merging this PR as there are collaborative commits which should remain separate.

I would like to thank Kreidos for all his help on this project. He was there to assist every step of the way and definitely deserves half the credit.

Fixes #240

### CODE REVIEW

File: scripts/globals/hunts.lua [hunk 1]
```diff
@@ -0,0 +1,1616 @@
...
+function tpz.hunts.onTrigger(player,npc,event)
+  local huntZone = player:getCharVar("[hunt]zone")
+  local huntId = player:getCharVar("[hunt]id")
+  local huntStatus = player:getCharVar("[hunt]status")
+  local scyldBits = bit.lshift(player:getCurrency("scyld"), 14)
+  local lockBit = bit.lshift(1, 24)
+  local registryZone = zone[player:getZoneID()]
+
+  -- one vana'diel day lockout timer after completing a hunt
+  if (VanadielYear() * 360) + VanadielDayOfTheYear() < player:getCharVar("[hunt]nextHunt") then
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: Could use `if os.time() < player:getCharVar("[hunt]nextHunt") then`

File: scripts/globals/hunts.lua [hunk 2]
```diff
@@ -0,0 +1,1616 @@
...
+
+  -- cancels hunt
+  elseif option == 3 then
+    player:messageSpecial(msg[3])
+    player:setCharVar("[hunt]status", 0)
+
+  -- cancels training regime and clears all vars
+  elseif option == 4 then
+    player:messageSpecial(msg[4])
+    tpz.regime.clearPlayerVars(player)
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: Was this changed to `clearRegimeVars`?

File: scripts/globals/hunts.lua [hunk 3]
```diff
@@ -0,0 +1,1616 @@
...
+  elseif option == 5 then
+    local huntZone = player:getCharVar("[hunt]zone")
+    local huntId = player:getCharVar("[hunt]id")
+    local scyldBounty = zone[huntZone].hunt[huntId].bounty
+
+    player:messageSpecial(msg[5])
+    player:messageSpecial(msg[6], scyldBounty, scylds)
+    player:addCurrency("scyld", scyldBounty)
+    -- give player evoliths here
+    player:setCharVar("[hunt]nextHunt", (VanadielYear() * 360) + (VanadielDayOfTheYear() + 1))
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: Could use `player:setCharVar("[hunt]nextHunt", getVanaMidnight())`

File: scripts/globals/hunts.lua (hunk 1 above)
Comment (Apocarypse) [reply scripts/globals/hunts.lua]: how about `if player:getCharVar("[hunt]nextHunt") < getVanaMidnight()then`

File: scripts/globals/hunts.lua (hunk 2 above)
Comment (Apocarypse) [reply scripts/globals/hunts.lua]: Yes! I'm glad you caught that.

File: scripts/globals/hunts.lua (hunk 1 above)
Comment (Kreidos) [reply scripts/globals/hunts.lua]: I like this idea. Ideally we should compare against a consistent source.

File: scripts/globals/hunts.lua [hunk 4]
```diff
@@ -0,0 +1,1616 @@
...
+function tpz.hunts.onTrigger(player,npc,event)
+  local huntZone = player:getCharVar("[hunt]zone")
+  local huntId = player:getCharVar("[hunt]id")
+  local huntStatus = player:getCharVar("[hunt]status")
+  local scyldBits = bit.lshift(player:getCurrency("scyld"), 14)
+  local lockBit = bit.lshift(1, 24)
+  local registryZone = zone[player:getZoneID()]
+
+  -- one vana'diel day lockout timer after completing a hunt
+  if player:getCharVar("[hunt]nextHunt") < getVanaMidnight() then
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: This should be checking `os.time()`, reason being that `getVanaMidnight()` very slightly varies in what it returns, even for the same day, so if you're lucky then `getVanaMidnight` will return a midnight that's maybe 1s before the `getVanaMidnight` that is saved in the char var. This should check `if os.time() < player:getCharVar("[hunt]nextHunt") then` (it's also checking the requirement backwards, this block should execute if the char is blocked)

Comment (Kreidos) [reply scripts/globals/hunts.lua]: I have a question. Since os.time() is lua native it always returns the system time; whereas getVanaMidnight ties into the time calculations and so could be affected by any offsets which are (or might) be implemented in the core. Couldn't that pose an issue to using os.time() which is completely independent of server time calculations?

File: scripts/globals/hunts.lua [hunk 5]
```diff
@@ -0,0 +1,1616 @@
...
+        [ 378] = { huntId = 157220, optionId = 2001 },
+        [ 634] = { huntId = 157221, optionId = 2009 },
+        [ 890] = { huntId = 174627, optionId = 2017 },
+
+      hunt =
+      {
+        [1577] = { pageId = 197, mobId = 17211561, bounty =  5, fee =   0 }, -- Stinging Sophie
+        [1585] = { pageId = 198, mobId = 17211714, bounty =  5, fee =   0 }, -- Maighdean Uaine
+        [1593] = { pageId = 199, mobId = 17211666, bounty =  5, fee =   0 }, -- Bedrock Barry
+        [1601] = { pageId = 200, mobId = 17215888, bounty =  5, fee =   0 }, -- Leaping Lizzy
```
Comment (cocosolos) [inline scripts/globals/hunts.lua:466]: I'm not sure if this is very common, but I happened to test this on Lizzy and she actually has 2 IDs, so might need to add the other one `17215868`.

File: scripts/globals/hunts.lua [hunk 6]
```diff
@@ -0,0 +1,1616 @@
...
+
+    player:messageSpecial(msg[5])
+    player:messageSpecial(msg[6], scyldBounty, scylds)
+    player:addCurrency("scyld", scyldBounty)
+    -- give player evoliths here
+    player:setCharVar("[hunt]nextHunt", getVanaMidnight())
+    tpz.hunts.clearHuntVars(player)
+
+    -- scylds cap at 1000
+    if player:getCurrency("scyld") + bounty > 1000 then
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: `bounty` is nil, is this supposed to be `scyldBounty`?

File: scripts/globals/hunts.lua (hunk 5 above)
Comment (Apocarypse) [reply scripts/globals/hunts.lua:466]: I asked about this and got no reply unfortunately. There are some NMs that have a single spawn point under one ID, and like 50 spawn points under another ID. In those cases, I opted for the 50. I don't know what the logic is there exactly.

File: scripts/globals/hunts.lua (hunk 6 above)
Comment (Apocarypse) [reply scripts/globals/hunts.lua]: Yes, I think you're right. I'll change it.

File: scripts/globals/hunts.lua [hunk 7]
```diff
@@ -0,0 +1,1616 @@
...
+
+  -- completes hunt
+  elseif option == 5 then
+    local huntZone = player:getCharVar("[hunt]zone")
+    local huntId = player:getCharVar("[hunt]id")
+    local scyldBounty = zone[huntZone].hunt[huntId].bounty
+
+    player:messageSpecial(msg[5])
+    player:messageSpecial(msg[6], scyldBounty, scylds)
+    player:addCurrency("scyld", scyldBounty)
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: Adding currency here and below?

File: scripts/globals/hunts.lua [hunk 8]
```diff
@@ -0,0 +1,1616 @@
...
+    tpz.regime.clearRegimeVars(player)
+
+  -- completes hunt
+  elseif option == 5 then
+    local huntZone = player:getCharVar("[hunt]zone")
+    local huntId = player:getCharVar("[hunt]id")
+    local scyldBounty = zone[huntZone].hunt[huntId].bounty
+
+    player:messageSpecial(msg[5])
+    player:messageSpecial(msg[6], scyldBounty, scylds)
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: This message should be moved to after you distribute the currency, then use the updated total.

File: scripts/globals/hunts.lua (hunk 4 above)
Comment (cocosolos) [reply scripts/globals/hunts.lua]: It's still using getVanaMidnight to set the time, so that's all accounted for. This check is just seeing if the current time is past what has been determined is the next vana midnight when that var was set.

File: scripts/globals/hunts.lua [hunk 9]
```diff
@@ -1586,19 +1586,19 @@ if huntEntry then
...
-    if player:getCurrency("scyld") + bounty > 1000 then
+    if player:getCurrency("scyld") + scyldBounty > 1000 then
        player:setCurrency("scyld", 1000)
+       player:messageSpecial(msg[5])
+       player:messageSpecial(msg[6], scyldBounty, scylds)
     else
-       player:addCurrency("scyld", bounty)
+       player:addCurrency("scyld", scyldBounty)
+       player:messageSpecial(msg[5])
+       player:messageSpecial(msg[6], scyldBounty, scylds)
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: This will still give the old total, go with this:
```lua
    -- scylds cap at 1000
    if player:getCurrency("scyld") + scyldBounty > 1000 then
       player:setCurrency("scyld", 1000)
    else
       player:addCurrency("scyld", scyldBounty)
    end
    player:messageSpecial(msg[5])
    player:messageSpecial(msg[6], scyldBounty, player:getCurrency("scyld"))
```

File: scripts/globals/hunts.lua [hunk 10]
```diff
@@ -0,0 +1,1615 @@
...
+function tpz.hunts.onEventFinish(player, csid, option)
+  local scylds = player:getCurrency("scyld")
+  local registryZone = zone[player:getZoneID()]
+  local huntEntry = registryZone.hunt[option]
+  local msg = registryZone.msg
+
+-- accepting hunt
+if huntEntry then
+    player:messageSpecial(msg[1])
+    player:messageSpecial(msg[2], huntEntry.fee, scylds)
```
Comment (cocosolos) [inline scripts/globals/hunts.lua]: These should be moved to after the fee is applied, and updated with `player:getCurrency("scyld")`

**Review by cocosolos — APPROVED** [review]
Tried out a few hunts, everything looks like it's working as it should. Good job!

File: scripts/globals/hunts.lua (hunk 5 above)
Comment (TeoTwawki) [reply scripts/globals/hunts.lua:466]: ~~tabling all the IDs of all these NMs is the wrong approach. Followup what all existing regimes do and include the regime ID at the mob, then match on regime ID instead of performing a lookup to see if that specific mob is in a table. We don't need to keep track of them all because its never going to change, and you already have that line there anyway. model it after the existing regimes instead of trying to centralize every bit of data to one place as this is a case where that just gets in the way.~~

~~`tpz.hunts.checkHunt(mob, player, isKiller)`
compare with
`tpz.regime.checkRegime(player, mob, 80, 1, tpz.regime.type.FIELDS)`
and
`tpz.regime.checkRegime(player, mob, 640, 2, tpz.regime.type.GROUNDS)`
you're trying to reinvent the wheel to separate hunts from these (understandable, a lot of code doesn't apply here) but missed why the regime ID was included.~~

now looking at this:
`tpz.hunts.checkHunt(mob, player, isKiller)`
We should not need isKiller at all as in retail all member who have the hunt regime active get credit and its not going to stack up (onMobDeath code will run once-per-member), so I suggest just go with:
`tpz.hunts.checkHunt(mob, player, RegimeIDhere)` to minimize your changes.

Edit: this could have been worded better by me, see coco's post which got straight to what it'd look like and didn't risk misunderstandings

Comment (TeoTwawki) [reply scripts/globals/hunts.lua:466]: p.s. if you're thinking "but then we need to keep track of which NMs go in which regime!" no, because the regime IDs will never shift. set once done for life. :)

Comment (Kreidos) [reply scripts/globals/hunts.lua:466]: I gotta disagree here on part of that. isKiller isn't necessary, you're right, but frankly I think having all the mobs tabled here with a simple lookup to a table is a much faster and better method than breaking out every ID into separate mob scripts. Regimes takes the ID it gets and combs through a table using a for loop anyway to find the mob which is far from elegant. This solution involves one direct check to one table and I gotta go with the performance method here.

Comment (Kreidos) [reply scripts/globals/hunts.lua:466]: I think this works well, and if you believe you have a better solution I welcome you to PR the files after this merges. :)

Comment (TeoTwawki) [reply scripts/globals/hunts.lua:466]: yeah no, I'm no opening a competing PR just because you prefer listing every NMs ID into the table and then trying to make workaround for the inherent shortcomings of that approach. 

A given NM can have multiple IDs. at a minimum would would need multiple ID entries. There is no reason we could not match on regime ID instead of mobID, loop or no loop.

Comment (cocosolos) [reply scripts/globals/hunts.lua:466]: Switching to `tpz.hunts.checkHunt(mob, player, RegimeIDhere)` would actually solve the multiple ID mobs issue all at once and would require minimal changes. `checkHunt` becomes:
```lua
    function tpz.hunts.checkHunt(mob, player, RegimeIDhere)
        local huntZone = player:getCharVar("[hunt]zone")
        local huntId = player:getCharVar("[hunt]id")
        local playerHunt = zone[huntZone].hunt[huntId]

        -- required NM has been defeated
        if player:getCharVar("[hunt]status") == 1 and huntId == RegimeIDhere then
           player:messageBasic(tpz.msg.basic.FOV_DEFEATED_TARGET + 20)
           player:setCharVar("[hunt]status", 2)
        end
    end
```
but that would also require removing all the mob IDs from the tables and updating all the mob files as well.

Comment (TeoTwawki) [reply scripts/globals/hunts.lua:466]: @cocosolos that is what I was going for. It does suck to re-edit all those mob scripts, but they all did have to have an edit to start with so its not like these didn't have code going to them. That said I will volunteer to make the mob script changes if apoc wants to take this road.

the alternative is harder - alterations to support multiple mobID elements and then the inevitable future problems that come with mobIDs later


((if anyone can come up with a 3rd option, I'm all ears)
