### PR TITLE
Bug with capped skills

### LINKED ISSUE #60: Combat/Magic skills can "cap out" earlier than they're supposed to.
<a href="https://github.com/Hozu"></img></a> **Issue by [Hozu](https://github.com/Hozu)**
_Friday Nov 06, 2015 at 20:24 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 2380_

----

If you reach the skill cap that you would have at the level of the mob (example, 153 skill for A+/- at mob level 50), the client will make the skill appear as capped. However, this can happen when your level is higher than the mob's level, which will prevent gaining skills even if you fight higher level mobs. The workaround for it is to either zone or un/re-equip the weapon to reset it.

### PR DESCRIPTION
**Pull request by jarmengaud**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes https://github.com/project-topaz/topaz/issues/60

### CODE REVIEW

File: src/map/utils/charutils.cpp [hunk 1]
```diff
@@ -2773,7 +2776,9 @@ namespace charutils
                     tier -= 1;
                     SkillAmount += 1;
                 }
+                // convert to 10th units
                 MaxSkill = MaxSkill * 10;
```
Comment (zach2good) [inline src/map/utils/charutils.cpp]: This isn't used any more at this point, can be removed

File: src/map/utils/charutils.cpp [hunk 2]
```diff
@@ -2724,6 +2724,9 @@ namespace charutils
         if ((PChar->WorkingSkills.rank[SkillID] != 0) && !(PChar->WorkingSkills.skill[SkillID] & 0x8000))
         {
             uint16 CurSkill = PChar->RealSkills.skill[SkillID];
+            uint16 CapSkill = battleutils::GetMaxSkill(SkillID, PChar->GetMJob(), PChar->GetMLevel());
+            // Max skill this mob level will allow.
```
Comment (zach2good) [inline src/map/utils/charutils.cpp]: Would be clearer to say "victim" or "target" instead of "mob" here, that's how it's called from `attack.cpp` and `battleutils.cpp` etc.

**Review by zach2good — CHANGES_REQUESTED** [review]
Looks good, just needs a tiny bit of cleanup. 

Fixing a bug is more important than 100% retail accuracy, but if you're here and you understand what's going on, getting this to be retail-accurate would be great. If not, open up a relevant issue when this is merged 👍

**Comment by jarmengaud** [comment]
I know that you can cap skill with decent challenge now, but I don't know the probability.
I would have difficulties trying to find the correct values from retail captures (besides i imagine it depends also on level, so would have to do several captures between 1 to 99...)
So i will just log an issue for the moment

**Review by 59blargedy — APPROVED** [review]
