### PR TITLE
only players currently on Dark Spark quest will get credit for the kill

### LINKED ISSUE #371: Credit for helping to defeat Dark Spark persists, even when not on AF hand quest
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
In the script for Dark Spark, [no check is done in the `onMobDeath` before setting a `charVar` giving the player credit for killing it](https://github.com/project-topaz/topaz/blob/master/scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua#L10-L12). This includes when you are assisting someone else with the quest and are not on the quest yourself.

If you later try to complete the quest yourself, and [manage to select the same torch as the last one which Dark Spark was spawned from (barring anything which would wipe the mob's local variable), you will instantly be given the key item without spawning it, due to already possessing credit](https://github.com/project-topaz/topaz/blob/master/scripts/zones/Castle_Zvahl_Baileys/npcs/Torch.lua#L19-L20).

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #371

### CODE REVIEW

File: scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua [hunk 1]
```diff
@@ -4,9 +4,16 @@
...
-require("scripts/globals/settings");
+require("scripts/globals/keyitems")
 -----------------------------------
 
 function onMobDeath(mob, player, isKiller)
-    player:setCharVar("BorghertzSparkKilled",1);
-end;
\ No newline at end of file
+    if
+        player:getCharVar("BorghertzSparkKilled") == 0 and
```
Comment (KnowOne134) [inline scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: mind if we change this to a local var same as the torch ID, if you logout with out touchng you would lose the torch refrence anyway. this particular var check on this line really isnt needed though since we have the other 2 checks.

**Review by KnowOne134 — APPROVED** [review]
using player:setLocalVar("BorghertzSparkKilled", 1) on mob death, removing if player:getCharVar("BorghertzSparkKilled") == 0 on the death and changing the var on the torch trigger for after killing DS to player:setLocalVar("BorghertzSparkKilled", 0)

sugestions are welcome from the others and works as is

File: scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua (hunk 1 above)
Comment (TeoTwawki) [reply scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: if you get DC'd do you have to repeat the fight though?

Comment (KnowOne134) [reply scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: Would have to anyway becuase it's also checking a local var vet on the torch on popping it and retrieving

Comment (TeoTwawki) [reply scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: I mean: whats retail do.

just..we're here anyway. ¯\\\_(ツ)\_/¯

Comment (megberry) [reply scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: Agree that we should mimic retail.  If someone with access can tell me how it works there, I can code to match.

Until then, how about this new commit?  This saves the torch used to spawn the crediting Spark to each player on the quest who helps kill it.  This way, the particular torch will persist per-player across logouts, or if someone else comes and kills a different Dark Spark before original player has a chance to touch the torch.

Comment (wrenffxi) [reply scripts/zones/Castle_Zvahl_Baileys/mobs/Dark_Spark.lua]: Agree that we should mimic retail.  If someone with access can tell me how it works there, I can code to match.

Until then, how about this new commit?  This saves the torch used to spawn the crediting Spark to each player on the quest who helps kill it.  This way, the particular torch will persist per-player across logouts, or if someone else comes and kills a different Dark Spark before original player has a chance to touch the torch.

**Review by KnowOne134 — APPROVED** [review]
i can agree on that, anything can be changed later

**Comment by wrenffxi** [comment]
Nyu tested this on retail.  Turns out it doesn't matter which torch is clicked: any of them will give the reward after Dark Spark is killed.  Also, if you kill Dark Spark, then log out and back in, then click a torch, you will be rewarded.

I have updated the PR to match retail testing.

**Review by ibm2431 — APPROVED** [review]
