### PR TITLE
Thunder Hawk and npcUtil key item option

### LINKED ISSUE #1292: Selbina Quest "The Rescue" If you complete a quest, you won't get a reward (Map of the Ranguemont Pass).
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

The parameter ("ki") in "npcUtil.completeQuest" seems to be wrong. (L40)

https://github.com/project-topaz/topaz/blob/5213062798b92405fb84ea90c3399bce75c4bf5e/scripts/zones/Selbina/npcs/Thunder_Hawk.lua#L37-L43

(L40) Use "keyItem" instead of "ki".
```
    elseif csid == 81 and npcUtil.completeQuest(player, OTHER_AREAS_LOG, tpz.quest.id.otherAreas.THE_RESCUE, {fame_area = SELBINA, keyItem = tpz.ki.MAP_OF_THE_RANGUEMONT_PASS, title = tpz.title.HONORARY_CITIZEN_OF_SELBINA, gil = 3000}) then

```

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #1292 

Rather than fixing Thunder Hawk's npcUtil option from **ki** to **keyItem** (See #1292), I decided to go the other way with the fix, and rename the option to **ki** for consistency.  Updated all references in codebase.

Also switched some references to the short-hand **tpz.ki**

### CODE REVIEW

File: scripts/globals/npc_util.lua [hunk 1]
```diff
@@ -349,8 +349,8 @@ function npcUtil.completeQuest(player, area, quest, params)
     end
 
     -- key item(s), fame, gil, bayld, xp, and title
-    if params["keyItem"] ~= nil then
-        npcUtil.giveKeyItem(player, params["keyItem"])
+    if params["ki"] ~= nil then
+        npcUtil.giveKeyItem(player, params["ki"])
```
Comment (zach2good) [inline scripts/globals/npc_util.lua:353]: For anyone else passing-by, this is the important change here!

Looks good, thanks! 👍

**Review by zach2good — APPROVED** [review]

File: scripts/globals/npc_util.lua (hunk 1 above)
Comment (TeoTwawki) [reply scripts/globals/npc_util.lua:353]: I'd really like to see the terms ki and keyItem be interchangeable everywhere. we have a high likelihood of future users using the "wrong" one no matter which we keep, so I'd rather we plan for it than simply swap out. I had thought we already did this for the actual global table, just not for the params we're using in the utils functions 

If the "right" one is nil and the other not, lets just populate/duplicate it over before we do the rest of execution.

Comment (zach2good) [reply scripts/globals/npc_util.lua:353]: Yeah, agree with this

Comment (zach2good) [reply scripts/globals/npc_util.lua:353]: @TeoTwawki 
Just for this case:
https://github.com/project-topaz/topaz/commit/f828092c6ff49a030f331626bf3ac82e915603e8
