### PR TITLE
Fix mobskill flag 0x010 (SKILLFLAG_REPLACE_ATTACK)

### LINKED ISSUE #1406: SetMobSkillAttack & tpz.mobMod.ATTACK_SKILL_LIST use TP
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

I observed and discussed this issue in https://github.com/project-topaz/topaz/pull/1388#issuecomment-712293072 and even made a [debug video](https://streamable.com/ojrve0) of this behavior.
`SetMobSkillAttack(list_id)` and `setMobMod(tpz.mobMod.ATTACK_SKILL_LIST, list_id)` are supposed to replace the default attack of a mob with the skill list ID passed to them and are currently mainly used for flying wyrms during their flight phase. The latter is actually not used at all but it serves the same purpose, and has the same flaw.

It can be observed however that **both of these** actually **use up all TP of the mob** on every regular hit as if it still was a mobskill instead of a regular attack. This is extremely bad, as the mob now does not generate any TP at all and does not use any mobskills.

This affects all flying wyrms like Jormungand, Tiamat, Ouryu and Wyrm and makes their flying phase extremely boring and well,...simply bugged.

### PR DESCRIPTION
**Pull request by MarianArlt**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Adds `isAttackReplacement()` to `mobskill.cpp` to prevent mobskill flag `SKILLFLAG_REPLACE_ATTACK = 0x010` from using up TP.

Fixes https://github.com/project-topaz/topaz/issues/1406
- [x] Successfully built and tested working locally

### CODE REVIEW

File: src/map/mobskill.cpp [hunk 1]
```diff
@@ -69,9 +69,14 @@ bool CMobSkill::isTwoHour() const
   return m_Flag & SKILLFLAG_TWO_HOUR;
 }
 
+bool CMobSkill::isAttackReplacement() const
+{
+  return m_Flag & SKILLFLAG_REPLACE_ATTACK;
```
Comment (zach2good) [inline src/map/mobskill.cpp:74]: This is probably from copy/pasting my comments ;)
4 spaces here please

**Comment by zach2good** [comment]
Putting this into a branch so I can make that change before I go to bed, thanks for this 👍

File: src/map/mobskill.cpp (hunk 1 above)
Comment (MarianArlt) [reply src/map/mobskill.cpp:74]: Yeah it was, sorry ^^
Thanks for correcting. There's a lot of inconsistency in that file regarding indentation.
