### PR TITLE
TOAU44: Fix black screen mid-fight

### LINKED ISSUE #1180: ToAU 44 Nashmeira's Plea
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Issues with ToAU 44:

- when you first click on the blank target in Nyzul, if you cancel and come back, you will no longer get the CS
  (you will skip it and need to directly click on the entry door)
- you can't call trusts
- when you have reached the 50% on Alexander, the intermediate cutscene triggers, but ends in a black screen.
  You will need to force close the client to exit this CS (you do get hit meanwhile, so will eventually die)

### PR DESCRIPTION
**Pull request by zach2good**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes: https://github.com/project-topaz/topaz/issues/1180
Superceeds: https://github.com/project-topaz/topaz/pull/1260

The order of events was wrong, so you ended up getting attacked while you were in CS. This ends up breaking your cs and results in you being trapped in a black screen.

Also discovered that `entityvsetPos()` doesn't correctly accept a table - like it is programmed to do. Gonna make an issue for that. Skirting around that here for now by using the table's members.

### CODE REVIEW

File: scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua [hunk 1]
```diff
@@ -34,12 +34,13 @@ end
 function onInstanceProgressUpdate(instance, progress)
     if (progress == 4) then
         local chars = instance:getChars()
+        local entryPos = instance:getEntryPos()
 
+        DespawnMob(ID.mob[59].RAZFAHD, instance)
         for i, v in pairs(chars) do
             v:startEvent(203)
+            v:setPos(entryPos.x, entryPos.y, entryPos.z, entryPos.rot)
```
Comment (ibm2431) [inline scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua:42]: Still have the `player:setPos(-444, -4, 420, 127)` down in the eventFinish~

Comment (zach2good) [reply scripts/zones/Nyzul_Isle/instances/nashmeiras_plea.lua:42]: _Oof!_ Nice catch!

**Review by TeoTwawki — APPROVED** [review]
So the solution did turn out to be relocating the player out of aggro distance at the time we trip the cs (while not accidentally zoning the player out of the instance :+1: by including a zoneID in our setPos)

**Review by ibm2431 — APPROVED** [review]

**Comment by zach2good** [comment]
Yeah, things just got confused by the setPos binding being screwwy with the return table from getEntryPos :(
