### PR TITLE
#569 - onMobSpawn (Linux) no spells

### LINKED ISSUE #569: trust not using magic or job ability
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
just tested the canary branch to see the changes made by PR #454 . Kupipi doesn't cast magic and naji still doesnt provoke. (Curilla no casting either, didn't try shantoto)

### PR DESCRIPTION
**Pull request by brianmask**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

change GetName() from packet_name to name
resolves #569 trust spells do not work on Linux

### CODE REVIEW

File: src/map/entities/trustentity.cpp [hunk 1]
```diff
@@ -49,11 +49,6 @@ CTrustEntity::CTrustEntity(CCharEntity* PChar)
     PAI = std::make_unique<CAIContainer>(this, std::make_unique<CPathFind>(this), std::make_unique<CTrustController>(PChar, this), std::make_unique<CTargetFind>(this));
 }
 
-const int8* CTrustEntity::GetName()
-{
-    return (const int8*)packetName.c_str();
```
Comment (TeoTwawki) [inline src/map/entities/trustentity.cpp:54]: Does the packetName still get sent in the packet to the client? As in if you cast `Trust: Selh'teus` does he pop on screen as `Selh'teus` or as `Selh_teus`/`Selh teus` ?

I think we need to do what allied mobs do, and have name and packetName as separate things, because both get used but for different purposes. Possibly this already happens because trusts are still mobs:
https://github.com/project-topaz/topaz/blob/8985d2af68876367592222836db1f8e5b15c8175/src/map/entities/mobentity.h#L244

If there's nothing to worry about then just mark my comment as resolved. :)

Comment (brianmask) [reply src/map/entities/trustentity.cpp:54]: Looks like it's properly pulling in the display name for the client.  I just checked Selh'teus, and his punctuation is correct.

**Review by ibm2431 — APPROVED** [review]
Thanks for looking into this, brianmask! Happy to have you here with us at Project Topaz!
