### PR TITLE
Optional dialogue for Justinius while doing "An Eternal Melody"

### LINKED ISSUE #864: Promathia Mission 2-4 (missing optional dialog)
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 
Please mark as easy fix, first issue
https://www.bg-wiki.com/bg/Promathia_Mission_2-4

missing:
(Optional) Speak with Justinius at (J-6) to learn of Ulmia's whereabouts.

He is still talking about the gate to aquadecuts

### PR DESCRIPTION
**Pull request by MarianArlt**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Adds a missing dialogue to Justinius while searching for Ulmia in Promathia mission 2-4 "An Eternal Melody".
Closes #864

### CODE REVIEW

File: scripts/zones/Tavnazian_Safehold/npcs/Justinius.lua [hunk 1]
```diff
@@ -12,12 +12,17 @@ function onTrade(player, npc, trade)
 end
 
 function onTrigger(player, npc)
+    local currentMission = player:getCurrentMission(COP)
+    local missionStatus = player:getCharVar("PromathiaStatus")
+    local missions = tpz.mission.id.cop
```
Comment (zach2good) [inline scripts/zones/Tavnazian_Safehold/npcs/Justinius.lua]: I couldn't be bothered to argue in the other PR, but since you like this pattern - let me ask you to modify how you use it:
```lua
    local copCurrentMission = player:getCurrentMission(COP)
    local copMissionStatus = player:getCharVar("PromathiaStatus")
    local copMissions = tpz.mission.id.cop
```

Granted, _this_ NPC is COP only, but this line:
```lua
if currentMission == missions.DISTANT_BELIEFS and missionStatus == 3 then
```
Gives nothing away if you don't already know what `DISTANT_BELIEFS` is.

**I think the point I'm trying and struggling to word clearly is:**
Aggressively cleaning up is great, optimising to reduce horizontal footprint is great, but not if they come with the cost of reducing information immediately available to the reader.

**Review by zach2good — CHANGES_REQUESTED** [review]
Content looks good.

I've tried to explain my issue with the caching pattern you've used, please adjust to using slightly more descriptive names 👍

**Comment by zach2good** [comment]
Great, thanks for baring with me :)
