### PR TITLE
Fix beastmen Howl animation

### LINKED ISSUE #1034: Yagudo Howl animation recently broken
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Yagudo Howl animation was fine 2 months ago, there musta been a change afterwards that broke it, now the animation looks all weird.

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #1034 

Howl (behemoth) was given to all beastmen.

### CODE REVIEW

File: sql/mob_skills.sql [hunk 1]
```diff
@@ -899,7 +899,7 @@ INSERT INTO `mob_skills` VALUES (1075,355,'ore_toss',0,7.0,2000,2000,4,0,0,0,0,0
 INSERT INTO `mob_skills` VALUES (1076,356,'head_butt',0,7.0,2000,2000,4,0,0,1,0,0,0);
 INSERT INTO `mob_skills` VALUES (1077,357,'shell_bash',0,7.0,2000,1000,4,0,0,0,0,0,0);
 INSERT INTO `mob_skills` VALUES (1078,358,'shell_guard',0,7.0,2000,3000,1,0,0,0,0,0,0);
-INSERT INTO `mob_skills` VALUES (1079,354,'howl',1,20.0,2000,1500,1,0,0,0,0,0,0);
+INSERT INTO `mob_skills` VALUES (1079,354,'howl',1,20.0,2000,1500,1,0,0,0,0,0,0); -- Yagudo/Orc/Quadav family Howl
```
Comment (59blargedy) [inline sql/mob_skills.sql]: from wiggo's actionview, this is actually dynamis divergence quadav only. there are a ton of different howls with same animation id. 

        ['Ruby Quadav-17129595'] = {
            [11] = {
                [762]  = {['name']="Howl",                           ['category']=11, ['id']=762,  ['animation']=354,  ['message']=194, },
        ['Yagudo Abbot-17129600'] = {
            [11] = {
                [764]  = {['name']="Howl",                           ['category']=11, ['id']=764,  ['animation']=354,  ['message']=194, },
            },
my guess is 760 or 766 have the same animation id and are the one for orcs. 
So: 
update howl 762 and 764 with correct animation id. assign correct howl to mob skill lists based on it.
pick 760 or 766 for orcs (gonna troll through captures, or maybe @project-topaz/researcher  can help grab a regular orc and prove it) and update accordingly.

**Comment by 59blargedy** [comment]
[766]  = {['name']="Howl",                           ['category']=11, ['id']=766,  ['animation']=354,  ['message']=194, },
Orc!!!! (THANKS TO @UynGH )

**Comment by TeoTwawki** [comment]
```sql

-- INSERT INTO `mob_skills` VALUES (757,501,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (758,502,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (759,503,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (760,504,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (761,505,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (762,354,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (763,507,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (764,354,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
-- INSERT INTO `mob_skills` VALUES (765,509,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
INSERT INTO `mob_skills` VALUES (766,354,'howl',1,20.0,2000,1500,1,0,0,0,0,0,0); -- Orc
-- INSERT INTO `mob_skills` VALUES (767,511,'bow',0,7.0,2000,1500,4,0,0,0,0,0,0);
```
that is a lot of howls.

**Comment by tankfest** [comment]
Updated all of the family howls with your guys' findings <3

**Review by 59blargedy — APPROVED** [review]

File: sql/mob_skills.sql [hunk 2]
```diff
@@ -582,11 +582,11 @@ INSERT INTO `mob_skills` VALUES (755,909,'fission',0,7.0,2000,1500,4,0,0,0,0,0,0
 -- INSERT INTO `mob_skills` VALUES (759,503,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
 -- INSERT INTO `mob_skills` VALUES (760,504,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
 -- INSERT INTO `mob_skills` VALUES (761,505,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
--- INSERT INTO `mob_skills` VALUES (762,354,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0);
+INSERT INTO `mob_skills` VALUES (762,354,'howl',0,7.0,2000,1500,4,0,0,0,0,0,0); -- Quadav
```
Comment (ibm2431) [inline sql/mob_skills.sql:585]: Is `mob_prepare_time` of 4 intended?

Comment (kaincenteno) [reply sql/mob_skills.sql:585]: omg welcome back @ibm2431  :heart_eyes_cat:

Comment (TeoTwawki) [reply sql/mob_skills.sql:585]: @ibm2431 that looks like `mob_valid_targets` is 4 there, prepare time the 1500 next to it. both look to be preexisting copypaste values (which are unlikely to be correct for most skills)

[in this case](https://github.com/project-topaz/topaz/blob/8c722838094c1aac0887eb3f13a3eb3168926933/src/map/entities/battleentity.h#L358)
```cpp
 TARGET_ENEMY = 0x04,
```
so that Quadav will buff me instead of itself! COME AT ME TURTLE MAN!

Comment (kaincenteno) [reply sql/mob_skills.sql:585]: > @ibm2431 that looks like `mob_valid_targets` is 4 there, prepare time the 1500 next to it. both look to be preexisting copypaste values (which are unlikely to be correct for most skills)
> 
> [in this case](https://github.com/project-topaz/topaz/blob/8c722838094c1aac0887eb3f13a3eb3168926933/src/map/entities/battleentity.h#L358)
> 
> ```c++
>  TARGET_ENEMY = 0x04,
> ```
> 
> so that Quadav will buff me instead of itself! COME AT ME TURTLE MAN!

lol i love your comments @TeoTwawki  they always cheer up my day =)

Comment (TeoTwawki) [reply sql/mob_skills.sql:585]: @kaincenteno I have invented a new sport. I call it turtle tipping. to play, turn off mob despawning. go deep into palborough mines, build up tp. anger a turtle on the other side of the gates where Zi'gi Boneeater spawns. he'll have to run all the way around to get to you. while you wait, anger a turtle on your side till he howls at you. All his friends will arrive just in time to eat a big pile of howl boosted aoe ws to the face.

forget exp per hr, turtles per hr is where its at Kain!
