### PR TITLE
Fixes for some recent quest issues

### LINKED ISSUE #1220: San d’Oria Quest "Exit the Gambler" Additional lines of dialogue
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/project-topaz/topaz/blob/3bc611df9cace45b9ebd3afe5635aa453fa886b1/scripts/zones/Northern_San_dOria/npcs/Nonterene.lua#L12-L14

If the quest "Exit the Gambler" is QUEST_ACCEPTED, the message of the NPC "Nonterene" should change.

if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.EXIT_THE_GAMBLER) == QUEST_ACCEPTED) then
  player:startEvent(523)
else
  player:startEvent(503)
end

### LINKED ISSUE #1222: San d’Oria Quest "The Pickpocket" Additional lines of dialogue
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If the quest "The Pickpocket" is QUEST_ACCEPTED, the message of the NPC  should change.

https://github.com/project-topaz/topaz/blob/8985d2af68876367592222836db1f8e5b15c8175/scripts/zones/West_Ronfaure/npcs/Colmaie.lua#L14-L16

    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED) then
      player:showText(npc, 7336)
    else
      player:showText(npc, ID.text.COLMAIE_DIALOG)
    end

https://github.com/project-topaz/topaz/blob/8985d2af68876367592222836db1f8e5b15c8175/scripts/zones/West_Ronfaure/npcs/Laillera.lua#L12-L14

    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED) then
      player:showText(npc, 7337)
    else
      player:showText(npc, ID.text.LAILLERA_DIALOG)
    end

https://github.com/project-topaz/topaz/blob/8985d2af68876367592222836db1f8e5b15c8175/scripts/zones/West_Ronfaure/npcs/Palcomondau.lua#L324-L327

    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED) then
      player:showText(npc, 7383)
    else
      player:showText(npc, ID.text.PALCOMONDAU_DIALOG)
    end
    --npc:wait(1500)

https://github.com/project-topaz/topaz/blob/5fde2aaa74fc534b59875e3c7825317208ed894a/scripts/zones/West_Ronfaure/npcs/Aaveleon.lua#L20-L31

    if sentrysPerilStatus < QUEST_COMPLETED and tradeFinished ~= 1 then
        player:startEvent(101) -- "Ow! Ouch! Gah... If only I'd remembered that ointment!"
    elseif tradeFinished == 1 and not player:hasItem(601) then
        player:startEvent(126, 601) -- "Did you lose it?"
    else
      if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED) then
        player:showText(npc, 7365)
      else
        player:showText(npc, ID.text.AAVELEON_HEALED) -- "My wounds are healed, thanks to you!"
      end
  end

https://github.com/project-topaz/topaz/blob/8985d2af68876367592222836db1f8e5b15c8175/scripts/zones/West_Ronfaure/npcs/Zovriace.lua#L1025-L1028

    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED) then
      player:showText(npc, 7384)
    else
      player:showText(npc, ID.text.ZOVRIACE_DIALOG)
    end
    npc:wait()

### LINKED ISSUE #1228: San d’Oria Quest "The Brugaire Consortium" Additional lines of dialogue
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If the quest "The Brugaire Consortium" is QUEST_COMPLETED, the NPC "Fontoumant" is unresponsive.

https://github.com/project-topaz/topaz/blob/2c5b97f1f742b54162b49dc842aee44085c41e9e/scripts/zones/Port_San_dOria/npcs/Fontoumant.lua#L44-L64

If the quest "The Brugaire Consortium" is QUEST_COMPLETED, the event "561" should be executed.

    local TheBrugaireConsortium = player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_BRUGAIRE_CONSORTIUM)

    if (TheBrugaireConsortium == QUEST_AVAILABLE) then
        player:startEvent(509)
    elseif (TheBrugaireConsortium == QUEST_ACCEPTED) then

        local prog = player:getCharVar("TheBrugaireConsortium-Parcels")
        if (prog == 11) then
            player:startEvent(511)
        elseif (prog == 21) then
            player:startEvent(512)
        elseif (prog == 31) then
            player:startEvent(515)
        else
            player:startEvent(560)
        end
    else
        player:startEvent(561)
    end

### LINKED ISSUE #1265: tutorial The item name in the message is missing.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/project-topaz/topaz/blob/b402b1b668f865723b11f9699b0b0b09bcf9268b/scripts/quests/tutorial.lua#L48-L49

            player:startEvent(npc_event_offset + 8, 0, 0, 0, tpz.ki.CONQUEST_PROMOTION_VOUCHER, 0, 0, 0)

### LINKED ISSUE #1269: Bastok Quest "Stardust" Add a message.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

If the quest "Stardust" is QUEST_ACCEPTED the message of the NPC should change.

https://github.com/project-topaz/topaz/blob/abfe5dda545545f060a761e894c79d55239ada02/scripts/zones/Bastok_Mines/npcs/Drangord.lua#L10-L12

```
    if (player:getQuestStatus(BASTOK, tpz.quest.id.bastok.STARDUST) == QUEST_ACCEPTED) then
        player:startEvent(97)
    else
        player:startEvent(21)
    end
```

### LINKED ISSUE #1275: Windurst Quest "A Pose by Any Other Name" item name in the message is missing.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

item name in the message is missing. (L64)

https://github.com/project-topaz/topaz/blob/abfe5dda545545f060a761e894c79d55239ada02/scripts/zones/Windurst_Waters/npcs/Angelica.lua#L57-L68

```
                player:startEvent(93, 0, desiredBody, 0, player:getCharVar("QuestAPoseByOtherName_equip")) -- reminder
```

### LINKED ISSUE #1308: Bastok Quest "Dark Puppet" Trigger point "???" is in the wrong position.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Wiki states the following.
https://www.bg-wiki.com/bg/Dark_Puppet
- Head to I-8 of the 1st floor map and you will find a ???.
- Trade the Darksteel Ingot to the ??? to spawn a NM: Gerwitz's Axe (NM). This will consume the ingot.

The SQL coordinates are wrong, as they are (H-12) in Ordelle's Caves MAP4. 
This is an outdated specification that was in place before the monster placement changes in the May 10, 2011 version of the game were taken into account.

```
INSERT INTO `npc_list` VALUES (17568176,'qm4','???',159,-51.779,27.694,-84.459,1,40,40,0,0,0,0,3,0x0000340000000000000000000000000000000000,0,NULL,0);
```

The spawn position of the mob "Gerwitzs_Axe" is also different.
```
INSERT INTO `mob_spawn_points` VALUES (17568135,'Gerwitzs_Axe','Gerwitz\'s Axe',46,-52,27,-81,255);
```

### LINKED ISSUE #1310: Bastok Quest "Blade of Evil" A treasure chest needs to be added to the cutscene.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

A treasure chest needs to be added to the cutscene.
The relevant cutscene is event ID "14" (L46)

https://github.com/project-topaz/topaz/blob/c2aa517599909fa0473f9739861ea8feb432d9ac/scripts/zones/Middle_Delkfutts_Tower/Zone.lua#L43-L50

A warning was output to the log.
```
[10/Oct] [22:44:09][Warning] Server need NPC <17420665>
```

If you add the following records, a treasure chest will appear in the cutscene.
```
INSERT INTO `npc_list` VALUES (17420665,'NOT_CAPTURED','     ',0,0.000,0.000,0.000,0,50,50,0,0,0,0,0,0x0000C00300000000000000000000000000000000,0,NULL,0);
```

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes for some of the quest issues recently opened by eyes-and-brain:

* Add dialog to Nonterene for quest "Exit the Gambler" [Fixes #1220]
* Add dialog to NPCs in West Ronfaure for quest "The Pickpocket" [Fixes #1222]
* Add post-quest dialog to Fontoumant for quest "The Brugaire Consortium" [Fixes #1228]
* Add arguments to event during tutorial quest [Fixes #1265]
* Add dialog to Drangord during quest "Stardust" [Fixes #1269]
* Add argument to event during quest "A Pose by Any Other Name" [Fixes #1275]
* Reposition QM and Gerwitz's Axe during quest "Dark Puppet" [Fixes #1308]
* Add csnpc to Middle Delkfutt's Tower [Fixes #1310]

### CODE REVIEW

File: scripts/zones/West_Ronfaure/npcs/Laillera.lua [hunk 1]
```diff
@@ -4,13 +4,18 @@
...
+require("scripts/globals/quests")
 -----------------------------------
 
 function onTrade(player, npc, trade)
 end
 
 function onTrigger(player, npc)
-    player:showText(npc, ID.text.LAILLERA_DIALOG)
+    if player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED then
+        player:showText(npc, ID.text.LAILLERA_DIALOG + 4)
```
Comment (TeoTwawki) [inline scripts/zones/West_Ronfaure/npcs/Laillera.lua:15]: Anytime you have to use showtext instead of messageSpecial, and the npc is -not- a shop, it is all but guaranteed to be the incorrect way to display the dialog. This is likely to be an event that our extractor tool was unable to handle.

**Comment by zach2good** [comment]
Based on what Teo said, I think it might be worth trying to replace these show-texts with their CS counterparts (if they're quickly accessible in event extractor)

File: scripts/zones/West_Ronfaure/npcs/Aaveleon.lua [hunk 2]
```diff
@@ -25,6 +25,8 @@ function onTrigger(player, npc)
         player:startEvent(101) -- "Ow! Ouch! Gah... If only I'd remembered that ointment!"
     elseif tradeFinished == 1 and not player:hasItem(601) then
         player:startEvent(126, 601) -- "Did you lose it?"
+    elseif player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED then
+        player:messageSpecial(ID.text.AAVELEON_HEALED + 26)
```
Comment (zach2good) [inline scripts/zones/West_Ronfaure/npcs/Aaveleon.lua:29]: 100 - Thank you for your help.
101 - Ow! Ouch! Gah... If only I'd remembered that ointment!
106 - What's this? I can't accept gifts from strangers.
118 - Thank you for your help.
126 - My wounds are healed, thanks to you!

File: scripts/zones/West_Ronfaure/npcs/Colmaie.lua [hunk 3]
```diff
@@ -12,7 +12,11 @@ function onTrade(player, npc, trade)
 end
 
 function onTrigger(player, npc)
-    player:showText(npc, ID.text.COLMAIE_DIALOG)
+    if player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED then
```
Comment (zach2good) [inline scripts/zones/West_Ronfaure/npcs/Colmaie.lua:15]: No event dumps :(

File: scripts/zones/West_Ronfaure/npcs/Laillera.lua (hunk 1 above)
Comment (zach2good) [reply scripts/zones/West_Ronfaure/npcs/Laillera.lua:15]: Yeah, no extracts for this one :(

File: scripts/zones/West_Ronfaure/npcs/Palcomondau.lua [hunk 4]
```diff
@@ -322,7 +323,11 @@ function onTrade(player, npc, trade)
 end
 
 function onTrigger(player, npc)
-    player:showText(npc, ID.text.PALCOMONDAU_DIALOG)
+    if player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.THE_PICKPOCKET) == QUEST_ACCEPTED then
```
Comment (zach2good) [inline scripts/zones/West_Ronfaure/npcs/Palcomondau.lua:326]: Nor this

**Comment by zach2good** [comment]
I maybe jumped the gun when I went and got the ID's for Aaveleon's CSs, he's the only one that's got anything listed in the events repo. You could put replacing their text's with CSs at the very very back of your TODO list, but it isn't major at all :)
