### PR TITLE
Change Conquest update + Guild Shop resets to JST time

### LINKED ISSUE #22: Guild Points
<a href="https://github.com/dazusu"></img></a> **Issue by [dazusu](https://github.com/dazusu)**
_Thursday Jun 04, 2015 at 12:49 GMT_
_Originally opened as DarkstarProject/darkstar - Issue 1519_

----

1. The daily turn-in item doesn't always reset. (meaning the same item for the same rank is requested sometimes 3-4 times in a row)
2. The "reset" period of when you can hand in items again should be affected by the "time offset" applied to the server for Japanese midnight; it is not (the NPC in game will tell you 3 in-game days), when in fact, due to the time offset on the server, it is more like 10 in-game days.

### LINKED ISSUE #552: Two different settings for server JP midnight time.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

**scripts\global\settings.lua:**
TIMEZONE_OFFSET = 9.0 -- Offset from UTC used to determine when JP Midnight is for the server.  Default is JST (+9.0).

**conf\map.conf:**
#Determine when JP midnight is.
vanadiel_time_offset: 8

Redundant settings, only one can/should be used.

Also if possible, maybe an option should be to pick it directly from the OS time.

### LINKED ISSUE #750: Cooking guild NPC does not accept bowl of puls for guild points
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Had a player report that NPC wasnt accepting bowl of puls for guild points even though it was asking for that. It did work on the previous item that the guild asked for. 

Looked up the item and it should be a guild item that is accepted based on:

https://ffxiclopedia.fandom.com/wiki/Puls

### LINKED ISSUE #875: Daily reset time does not honor "JP Midnight" default setting
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Things that are supposed to reset daily or weekly (tally, guild items,...), are not resetting at JP midnight with default configuration, even though by default:
TIMEZONE_OFFSET = 9.0 -- Offset from UTC used to determine when "JP Midnight" is for the server.  Default is JST (+9.0). 

If you look at the time_server.cpp code, you will see things like:
    //Midnight
    if (CVanaTime::getInstance()->getSysHour() == 0 && CVanaTime::getInstance()->getSysMinute() == 0)

so it is hardcoded that reset will happen at midnight for the server local time zone. And cannot be changed by a configuration either.

Would probably fix:
https://github.com/project-topaz/topaz/issues/22

### PR DESCRIPTION
**Pull request by Kreidos**
+ Move Guild Reset over to JST midnight instead of local.
+ fix + remove single-purpose vars from global Vanatime class.
+ Move Conquest over to JST instead of local time.
+ Migrate Lua over to new JST function for getMidnight.

Fixes #750
Fixes #875
Fixes #22 
Closes #552 

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

**Comment by Kreidos** [comment]
Moved conquest updates over to JST as well, because why not!

File: scripts/globals/common.lua [hunk 1]
```diff
@@ -46,29 +46,10 @@ end
...
-    -- Midnight adjusted for timezone, then timezone offset * 3600 to get us where we want to be.
-    local finaltime = midnight + timezone - (TIMEZONE_OFFSET * 3600)
-    -- And make sure that the offset midnight isn't already passed
-    if day ~= nil and finaltime <= day or day == nil and finaltime <= os.time() then
-        finaltime = finaltime + 86400
-    end
-
-    return finaltime
-end
+getMidnight = JstMidnight
```
Comment (TeoTwawki) [inline scripts/globals/common.lua:52]: I'ma  lil too late, but I would have said just give it the name we had already been using and skip the assignment lol. Thanks for making this happen Kreidos.

**Comment by ibm2431** [comment]
Explanation for those not following Discord:
Settings to change when "midnight" occurs can't make in-game things happen _at_ the midnight in an _arbitrary_ timezone - they can only be used to change _your_ midnight _from_ your local midnight _to_ JST, so you can run the server _without having to change your system's timezone_.

Settings to change when in-game midnight "is" (ie: making things happen at midnight in _your local_ timezone) **_can't_** function as desired. **The client is hardcoded to _always expect certain things_ to occur at midnight in JST. No server-side shenanigans can ever change these hardcoded client events and expectations.**

File: scripts/globals/common.lua (hunk 1 above)
Comment (Kreidos) [reply scripts/globals/common.lua:52]: I considered that. We can still call it either way, just that I was concerned the name wasn't descriptive enough before, and that it didn't follow capitalization standards the way other Luautils functions do. Plus, maybe there'd be momentum behind the existing name. And I questioned changing 13 other files to match. :P I'm indifferent if someone wants to go ahead and change the 13 usages to the new name.

**Comment by TeoTwawki** [comment]
Before anyone brings up any formerly JP midnight things that now aren't: _those_ ones aren't hardcoded into the event in the client like we're talking about, those just used it for a trigger condition. _Those_ can still change. What time is actually JP Midnight cannot, as ibm2431 has stated.

**Comment by ibm2431** [comment]
Basically:
- We can make an NPC accept a trade whenever we want. (trigger condition)
- We can't make guilds change their pattern at any time other than true JST. (hardcoded client expectation)

**Comment by Kreidos** [comment]
> Before anyone brings up any formerly JP midnight things that now aren't: _those_ ones aren't hardcoded into the event in the client like we're talking about, those just used it for a trigger condition. 

I believe all things should correctly be JST-midnight now, but if things aren't please open issue or discuss on discord; should be very easy to *make* it correct. :)
