### PR TITLE
Fixes A Sentry's Peril and npc_utils Glenne's script

### LINKED ISSUE #1099: San d'Oria Quest "A Sentry's Peril" is not complete.
Glenne.lua

```
function onTrade(player, npc, trade)
    if (player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL) == QUEST_ACCEPTED and
        trade:hasItemQty(601, 1) and count == 1) then
            player:startEvent(513)
            npc:wait()
    end

end
```

Even when I traded "Ointment Case" to Glenne, there was no response.
There is a "count == 1" condition, but the "count" variable appears to be undefined.

### PR DESCRIPTION
**Pull request by tankfest**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #1099

### CODE REVIEW

File: scripts/zones/Southern_San_dOria/npcs/Glenne.lua [hunk 1]
```diff
@@ -38,69 +39,37 @@ function onPath(npc)
...
-            player:messageSpecial(ID.text.ITEM_OBTAINED, 12832) -- Bronze Subligar
-            player:addFame(SANDORIA, 30)
-            player:completeQuest(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL)
-        end
+    if csid == 510 and option == 0 and npcUtil.giveItem(player, 600) then
+        player:addQuest(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL)
+    elseif csid == 644 then
+        npcUtil.giveItem(player, 600)
+    elseif csid == 513 and npcUtil.completeQuest(player, SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL, {item = 12832, fame = 30, title = tpz.title.RONFAURIAN_RESCUER}) then
+        player:tradeComplete()
```
Comment (wrenffxi) [inline scripts/zones/Southern_San_dOria/npcs/Glenne.lua]: If you're checking items in the trade via `npcUtil.tradeHas()`, then you should close the trade via `player:confirmTrade()` rather than `player:tradeComplete()`.

confirmTrade will consume only the items you checked for, and will return to player any excess items placed into the trade window.

tradeComplete will consume all items in the trade window.

**Comment by tankfest** [comment]
Nyu went through and captured correct behavior and dialogue for this quest.  I think it's 99% retail now.

File: scripts/zones/West_Ronfaure/npcs/Aaveleon.lua [hunk 2]
```diff
@@ -4,22 +4,30 @@
...
-    if player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL) == QUEST_ACCEPTED then
-        if npcUtil.tradeHas(trade, 600) then
-            player:startEvent(100)
-        else
-            player:startEvent(118)
-        end
+    if npcUtil.tradeHas(trade, 600) then -- Ointment
+        player:startEvent(100) -- He accepts the ointment and gives the player the empty case to return to his wife.
+    elseif player:getQuestStatus(SANDORIA, tpz.quest.id.sandoria.A_SENTRY_S_PERIL) < QUEST_COMPLETED then
+        player:startEvent(106) -- "What's this? I can't accept gifts from strangers."  He stops saying this after quest complete.
```
Comment (59blargedy) [inline scripts/zones/West_Ronfaure/npcs/Aaveleon.lua:16]: does he just not respond to trades post quest completion?

Comment (tankfest) [reply scripts/zones/West_Ronfaure/npcs/Aaveleon.lua:16]: Yes, Nyu confirmed.

**Review by zach2good — APPROVED** [review]
Looks fine at a glance, but I've been seeing a _slew_ of this recently:

```
[] that I've tested my code since the last commit in the PR, and will test after any later commits
^----
```

Test yo' changes, please!
