### PR TITLE
a pose by any other name: angelica cleanup

### LINKED ISSUE #1123: Windurst Quest "A Pose by Any Other Name" may not start.
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

https://github.com/project-topaz/topaz/blob/ef5935b2ed20a6710422cfebd8b0f2940addbaf1/scripts/zones/Windurst_Waters/npcs/Angelica.lua#L18-L42

There seems to be a shortage of "tpz.job.RDM" in the quest's starting conditions. (L35)

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Clean up Angelica's NPC script for quest "[A Pose By Any Other Name](https://ffxiclopedia.fandom.com/wiki/A_Pose_by_Any_Other_Name)"

* table the items needed by each job [Fixes #1123]
* local a few variables
* npcUtilify quest complete
* prevent picking up quest if you're already wearing the correct body item
* move setCharVars from onTrigger to onEventFinish

### CODE REVIEW

**Review by zach2good — APPROVED** [review]
My god, so much better, thanks!

File: scripts/zones/Windurst_Waters/npcs/Angelica.lua [hunk 1]
```diff
@@ -4,62 +4,81 @@
...
-require("scripts/globals/settings")
 require("scripts/globals/keyitems")
+require("scripts/globals/npc_util")
 require("scripts/globals/quests")
-require("scripts/globals/titles")
 require("scripts/globals/status")
+require("scripts/globals/titles")
 -----------------------------------
 
+local poseItems = {
```
Comment (TeoTwawki) [inline scripts/zones/Windurst_Waters/npcs/Angelica.lua]: inline table brace detected :alarm_clock:

**Review by TeoTwawki — APPROVED** [review]
looks much better
