### PR TITLE
Fix buying Magicked Astrolabe

### LINKED ISSUE #418: Churano-Shurano NPC doesn't behave properly when trading for the magicked astrolabe.
**_I have:_**

- [x] searched existing issues (http://github.com/project-topaz/topaz/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Talk to Churano-Shurano without the magicked astrolabe key item in your inventory, and your char var "Astrolabe" == 0.  He will ask you if you want to buy it for 10k, if you select yes, nothing happens.  If you talk to him again, he gives the same event (it should be a diff one with diff dialogue), and may or may not sell the astrolabe to you correctly.  The current script doesn't clean up its unused char var, "Astrolabe", after the trade is completed either.

### PR DESCRIPTION
**Pull request by ibm2431**
The first param for the event update dictates the option sent by the client back to the server onEventFinish. It needed to be the key item ID for the Astrolabe for the event to not display the "partial payment" line.

Fixes #418 

**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](https://github.com/project-topaz/topaz/blob/master/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

### CODE REVIEW

File: scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua [hunk 1]
```diff
@@ -1,37 +1,45 @@
...
+end
 
-function onEventFinish(player,csid,option)
-    if (csid == 1080 and option == 1) then
-        player:setCharVar("Astrolabe", 1);
-    elseif (csid == 1081 and option == 1 and player:delGil(10000)) then
-        player:messageSpecial(ID.text.KEYITEM_OBTAINED,tpz.ki.MAGICKED_ASTROLABE);
-        player:addKeyItem(tpz.ki.MAGICKED_ASTROLABE);
+function onEventFinish(player, csid, option)
+    if (csid == 1080) and (option ~= tpz.ki.MAGICKED_ASTROLABE) then
```
Comment (TeoTwawki) [inline scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua]: them extra parens

File: scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua [hunk 2]
```diff
@@ -1,37 +1,45 @@
...
+        player:setLocalVar("Astrolabe", 1)
+    elseif (csid == 1080 or csid == 1081) and (option == tpz.ki.MAGICKED_ASTROLABE) and (player:getGil() >= 10000) then
```
Comment (TeoTwawki) [inline scripts/zones/Windurst_Waters/npcs/Churano-Shurano.lua]: here too
