### PR TITLE
Flyers for Regine: Act III (Finale)

### LINKED ISSUE #667: Flyers for Regine quest (crash and possible improvements).
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [x] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Hello.

Vyvin reported this issue on Discord.

> [...] turning in a flyer to Guilberdrier in Northern San D'Oria for the Fliers for Regine quest crashes my server [...]

I checked on the latest Canary build and compared to this retail video capture of the quest: https://www.youtube.com/watch?v=Se10PQ_nzaY and BGWiki: https://www.bg-wiki.com/bg/Flyers_for_Regine.

~~Trading a Magicmart Flyer indeed crashes topaz_game.exe~~ but I found several possible improvements/differences trying to reproduce this and comparing to the video and Wiki above:

~~When you receive the 15 Magicmart Flyers from Regine (at 1:06 in the video) there should be only one line displayed, obtaining them. On Topaz there's two:
img_20200530_160619~~

Every NPC to which you need to trade a fish should say something when you pass near them ("NPC looks over curisouly for a moment.") at 1:36 (and throughout), on Topaz there's none.

~~There's an extra message displayed when you trade a Magicmart Flyer ("You've handed out X flyer(s)!") on Topaz, shouldn't be there at 3:17 (and throughout).
img_20200529_024101~~

Wasn't able to continue the quest because of said crash above but looks like Vyvin fixed it by doing this:
> [...] I edited his lua script to match Capiria's but with his variables for the FFR quest, Also noticed that Coullene's variable was missing an l in hers
this change stopped the crashing, and allowed me to finish the quest

Thank you!

Edit: mostly fixed by https://github.com/project-topaz/topaz/pull/682! Thank you, @wrenffxi.

### PR DESCRIPTION
**Pull request by wrenffxi**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [x] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

Fixes #667 
Relates to #682 

This PR fixes the remaining issues with quest "Flyers for Regine" and neatens the code.

* When approaching tradable NPCs, you now receive a message "So-and-so looks over curiously for a moment."
* The "looks over curiously" messages are now found by offsets from a base message.
* The after-trading dialog from each NPC is now prefixed with their name.
* Trade progress is now tracked with a single bitmask rather than 15 vars.
* Code for defining approach regions and trading flyers is now contained in scripts/quests/flyers_for_regine

### CODE REVIEW

File: scripts/zones/Port_San_dOria/npcs/Regine.lua [hunk 1]
```diff
@@ -51,32 +53,22 @@ end;
...
-            player:setCharVar("tradeBoncort",0);
-            player:setCharVar("tradeCoullene",0);
-            player:setCharVar("tradeLeuveret",0);
-            player:setCharVar("tradeBlendare",0);
-            player:setCharVar("tradeMaugie",0);
-            player:setCharVar("tradeAdaunel",0);
-            player:setCharVar("tradeRosel",0);
-            player:setCharVar("FFR",0);
+    if csid == 601 then
+        player:setCharVar("FFR", 1)
```
Comment (ibm2431) [inline scripts/zones/Port_San_dOria/npcs/Regine.lua:57]: I know this was always here, but do we happen to know if the pre-quest CS only happens once _ever_, or just once per zone?

File: scripts/quests/flyers_for_regine.lua [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+}
+
+-------------------------------------------------
+-- public functions
+-------------------------------------------------
+
+quests.flyers_for_regine.initZone = function(zone)
+    local zoneId = zone:getID()
+
+    for k, v in pairs(npcData) do
```
Comment (ibm2431) [inline scripts/quests/flyers_for_regine.lua:49]: It might be possible to reduce the number of loops by taking advantage of how every zone always has 5. You'd need a _tiny_ bridge table linking a zone ID to an offset, but once you have it:
```lua
-- pseudo
local zone_offsets = {
  [tpz.zone.PORT_SAN_DORIA] = 0,
  [tpz.zone.NORTHERN_SAN_DORIA] = 1,
}

quests.flyers_for_regine.initZone = function(zone)
local offset = ffr.zoneOffset[zone_id]
for i = offset, offset + 5 do
  local npc = npcData[i]
  registerRegion(npc.region, npc.x)
```

Although it'd only save _just a few_ cycles, so it's up to you.

File: scripts/quests/flyers_for_regine.lua [hunk 3]
```diff
@@ -0,0 +1,89 @@
...
+        end
+    end
+end
+
+quests.flyers_for_regine.onRegionEnter = function(player, region)
+    local zoneId = player:getZoneID()
+    local regionId = region:GetRegionID()
+
+    for k, v in pairs(npcData) do
+        if v.zone == zoneId and v.region == regionId then
```
Comment (ibm2431) [inline scripts/quests/flyers_for_regine.lua:61]: regionEnter checks could then use the offsets too, so you're only checking up to 5 regions per check, as opposed to potentially up to 15.

**Review by ibm2431 — APPROVED** [review]
Finally, my most-hated quest looks respectable!

Comments aren't merge-blocking; just thoughts~

File: scripts/zones/Port_San_dOria/npcs/Regine.lua (hunk 1 above)
Comment (wrenffxi) [reply scripts/zones/Port_San_dOria/npcs/Regine.lua:57]: I'm working off a video -- no retail access -- so can't answer this off the top of my head.  I added this question to an already-open Flyers for Regine question I have in the FFXICaptures discord.

File: scripts/quests/flyers_for_regine.lua (hunk 2 above)
Comment (wrenffxi) [reply scripts/quests/flyers_for_regine.lua:49]: I'd like to leave this PR as is for now.  However, I'm going to revisit FFR once I have answers to questions in Captures discord.  When I do the next (last?) FFR PR, I'll include this change too.

Comment (ibm2431) [reply scripts/quests/flyers_for_regine.lua:49]: Sounds good - I guess I jumped the gun when coming up with a target branch name for this. 😅

**Review by cocosolos — APPROVED** [review]

File: scripts/quests/flyers_for_regine.lua (hunk 2 above)
Comment (TeoTwawki) [reply scripts/quests/flyers_for_regine.lua:49]: who knew Regine was a one winged angel? ¯\\_(ツ)\_\/¯
