### PR TITLE
Corrects chocobo digging loot pools

### LINKED ISSUE #848: [Chocobo Digging] Wajaom Woodlands Chocobo Digging is using the same reward list as Bhaflau Thickets
**_I have:_**

- [x] searched existing issues (http://project-topaz.com/issues/) to see if the issue has already been opened
- [ ] checked the commit log to see if the issue has been resolved since my server was last updated

**_Additional Information_** (Steps to reproduce/Expected behavior) **:** 

Chocobo digging in Wajaom Woodlands will result in receiving items that should be found in Bhaflau Thickets. After investigating on my side, I noticed that the rewards in chocobo_digging.lua are the same.

[tpz.zone.WAJAOM_WOODLANDS] = -- 51
    {
        {  770,  50, digReq.NONE    },
        { 2150,  60, digReq.NONE    },
        {  622, 197, digReq.NONE    },
        { 2155,  23, digReq.NONE    },
        {  739,   5, digReq.NONE    },
        {17296, 133, digReq.NONE    },
        {  703,  69, digReq.NONE    },
        { 2213, 135, digReq.NONE    },
        {  838,  21, digReq.NONE    },
        { 4096, 100, digReq.NONE    }, -- all crystals
        { 1255,  10, digReq.NONE    }, -- all ores
        {  688, 144, digReq.BURROW  },
        {  702,  14, digReq.BURROW  },
        {  690,  23, digReq.BURROW  },
        { 1446,   3, digReq.BURROW  },
        {  700,  14, digReq.BURROW  },
        {  699,  37, digReq.BURROW  },
        {  701,  28, digReq.BURROW  },
        {  696,  23, digReq.BURROW  },
        {  678,   9, digReq.BORE    },
        {  645,   3, digReq.BORE    },
        {  768, 193, digReq.BORE    },
        {  737,  22, digReq.BORE    },
        { 2475,   3, digReq.BORE    },
        {  738,   3, digReq.BORE    },
        { 4570,  10, digReq.MODIFIER},
        { 4487,  11, digReq.MODIFIER},
        { 4409,  12, digReq.MODIFIER},
        { 1188,  10, digReq.MODIFIER},
        { 4532,  12, digReq.MODIFIER},
    },
    [tpz.zone.BHAFLAU_THICKETS] = -- 52
    {
        {  770,  50, digReq.NONE    },
        { 2150,  60, digReq.NONE    },
        {  622, 197, digReq.NONE    },
        { 2155,  23, digReq.NONE    },
        {  739,   5, digReq.NONE    },
        {17296, 133, digReq.NONE    },
        {  703,  69, digReq.NONE    },
        { 2213, 135, digReq.NONE    },
        {  838,  21, digReq.NONE    },
        { 4096, 100, digReq.NONE    }, -- all crystals
        { 1255,  10, digReq.NONE    }, -- all ores
        {  688, 144, digReq.BURROW  },
        {  702,  14, digReq.BURROW  },
        {  690,  23, digReq.BURROW  },
        { 1446,   3, digReq.BURROW  },
        {  700,  14, digReq.BURROW  },
        {  699,  37, digReq.BURROW  },
        {  701,  28, digReq.BURROW  },
        {  696,  23, digReq.BURROW  },
        {  678,   9, digReq.BORE    },
        {  645,   3, digReq.BORE    },
        {  768, 193, digReq.BORE    },
        {  737,  22, digReq.BORE    },
        { 2475,   3, digReq.BORE    },
        {  738,   3, digReq.BORE    },
        { 4570,  10, digReq.MODIFIER},
        { 4487,  11, digReq.MODIFIER},
        { 4409,  12, digReq.MODIFIER},
        { 1188,  10, digReq.MODIFIER},
        { 4532,  12, digReq.MODIFIER},
    },

### PR DESCRIPTION
**Pull request by Aeshur**
**_I affirm:_**
- [x] that I agree to Project Topaz's [Limited Contributor License Agreement](http://project-topaz.com/blob/release/CONTRIBUTOR_AGREEMENT.md), as written on this date
- [] that I've _tested my code_ since the last commit in the PR, and will test after any later commits

All of the current rates/weights follow the ffxiclopedia ones that are listed similar to whoever previously wrote these, as there does not seem to be any other websites available with weights/data. For now I just used the ffxiclopedia weights exactly, but I'm thinking that the rarity tiers probably all have the same rate applied to an item, rather than specific drop rates for each individual item -- similar to Treasure Hunter. If that's agreed upon I am more than willing to go back and update them.

Fixed Wajaom Woodlands, was previously copy pasted from Bhaflau Thickets
	Fixes #848 
	https://ffxiclopedia.fandom.com/wiki/Wajaom_Woodlands/Chocobo_Digging

Updated West Ronfaure rates to match wiki
	https://ffxiclopedia.fandom.com/wiki/West_Ronfaure/Chocobo_Digging

Fixed Valkurm Dunes, was previously copy pasted from Western Altepa Desert.
	https://ffxiclopedia.fandom.com/wiki/Valkurm_Dunes/Chocobo_Digging

Fixed West Sarutabaruta, was previously copy pasted from East Sarutabaruta
	https://ffxiclopedia.fandom.com/wiki/West_Sarutabaruta/Chocobo_Digging

Fixed Tahrongi Canyon, was previously copy pasted from Western Altepa Desert.
	https://ffxiclopedia.fandom.com/wiki/Tahrongi_Canyon/Chocobo_Digging

Fixed Sauromugue Champaign, was previously copy pasted from Western Altepa Desert.
	https://ffxiclopedia.fandom.com/wiki/Sauromugue_Champaign/Chocobo_Digging

### CODE REVIEW

File: scripts/globals/chocobo_digging.lua [hunk 1]
```diff
@@ -121,30 +121,30 @@ local digInfo =
...
+        {  700,   4, digReq.BURROW  },
+        {  699,  31, digReq.BURROW  },
+        {  701,   4, digReq.BURROW  },
+        {  696,  35, digReq.BURROW  },
+        {  678,   1, digReq.BORE    },
+        {  645,   1, digReq.BORE    },
+        {  768,  98, digReq.BORE    },
         {  737,  22, digReq.BORE    },
         { 2475,   3, digReq.BORE    },
+		{  739,   1, digReq.BORE    },
```
Comment (tankfest) [inline scripts/globals/chocobo_digging.lua]: this tab indent can be converted into spaces

**Comment by TeoTwawki** [comment]
> but I'm thinking that the rarity tiers probably all have the same rate applied to an item, rather than specific drop rates for each individual item -- similar to Treasure Hunter.

I think so as well. Likely the case for many things too, maybe treasure chests/coffers and even H.E.L.M. But don’t know for sure. With enough _reliable_ data we could make a good guess maybe.

File: scripts/globals/chocobo_digging.lua (hunk 1 above)
Comment (Aeshur) [reply scripts/globals/chocobo_digging.lua]: Fixed, thanks for all the help with git gui as well!

**Review by zach2good — APPROVED** [review]
